
[project]
name = "schemapack"
version = "1.0.0"
description = "Make your JSON Schemas sociable and create linked data model."
dependencies = [
    "pydantic >=2, <3",
    "pydantic_settings >=2, <3",
    "PyYAML >=6.0.1, <7",
    "jsonschema >=4.19.2, <5",
    "immutabledict >=3.0.0, <4",
]

[project.urls]
# please adapt to package name
Repository = "https://github.com/ghga-de/schemapack"
