
[project]
name = "schemapack"
version = "2.0.0-alpha.3"
description = "Make your JSON Schemas sociable and create linked data model."
dependencies = [
    "pydantic >=2, <3",
    "pydantic_settings >=2, <3",
    "ruamel.yaml ~= 0.18.6",
    "jsonschema >=4.19.2, <5",
    "immutabledict >=3.0.0, <4",
]

[project.urls]
# please adapt to package name
Repository = "https://github.com/ghga-de/schemapack"
