
[project]
name = "schemapack"
version = "3.1.0"
description = "Make your JSON Schemas sociable and create linked data models."
dependencies = [
    "pydantic >=2, <3",
    "pydantic_settings >=2, <3",
    "ruamel.yaml ~=0.18.6",
    "jsonschema >=4.19.2, <5",
    "arcticfreeze ~=0.1.1",
    "rich >13, <14",
    "typer >= 0.16.0",
]
classifiers = [
    "Development Status :: 1 - Planning",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.12",
    "License :: OSI Approved :: Apache Software License",
    "Topic :: Internet :: WWW/HTTP :: HTTP Servers",
    "Topic :: Software Development :: Libraries",
    "Intended Audience :: Developers",
]

[project.urls]
# please adapt to package name
Repository = "https://github.com/ghga-de/schemapack"

[project.scripts]
schemapack = "schemapack.__main__:cli"
